kind: pipeline
name: build and publish

steps:
  - name: build
    image: archxlinux/archxlinux
    pull: always
    privileged: true
    commands:
      - yes | pacman -Sy git wget elfkickers fakeroot gzip 
      - cp makepkg /usr/bin
      - echo -e $SIGNATURE | gpg --import
      - ./build.sh || true
    environment:
      SIGNATURE:
        from_secret: signature
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
