kind: pipeline
name: build and publish

steps:
  - name: build
    image: archxlinux/archxlinux
    pull: always
    privileged: true
    commands:
      - pacman-key --recv-keys 7CE735AE27960124DC20549D842ABE3AA3C5FCD7
      - pacman-key --lsign-key 7CE735AE27960124DC20549D842ABE3AA3C5FCD7
      - yes | pacman -Sy git wget base-devel archxlinux-keyring
      - cp makepkg /usr/bin
      - bash -x ./build.sh || true
    environment:
      SIGNATURE:
        from_secret: signature
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
