kind: pipeline
name: build and publish

steps:
  - name: build
    image: archxlinux/archxlinux
    pull: always
    privileged: true
    commands:
      - yes | pacman -Sy git wget base-devel
      - cp makepkg /usr/bin
      - echo -e $SIGNATURE | gpg --import
      - pacman --recv-keys DA6BDDD08D26A04AAC997968C79769BC07914012
      - pacman --lsign-key DA6BDDD08D26A04AAC997968C79769BC07914012
      - bash -x ./build.sh || true
    environment:
      SIGNATURE:
        from_secret: signature
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /tmp/cache
